---
- hosts: all
  tasks:
    #- name: install openssh-server
#  #hosts: java
#  tasks:
#    - name: Check openssh are installed
#      dnf:
#        name: "{{ packages }}"
#        state: present
#      vars:
#        packages:
#          - openssh-server


  - name: Enable openssh-server
    service:
      name: sshd
      enabled: yes
  
  - name: Start openssh-server
    service:
      name: sshd
      state: started